# Generated by Django 5.0.7 on 2026-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='eine kleine Zusammenfassung über mich.', max_length=500, verbose_name='Über mich')),
                ('location', models.CharField(blank=True, help_text='Der Ort, an dem ich mich befinde.', max_length=30, verbose_name='Ort')),
            ],
        ),
    ]
