# Generated by Django 4.2.11 on 2024-04-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="eine kleine Zusammenfassung über mich.",
                        max_length=500,
                        verbose_name="Über mich",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Der Ort, an dem ich mich befinde.",
                        max_length=30,
                        verbose_name="Ort",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Der Benutzer, dem dieses Profil gehört.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzername",
                    ),
                ),
            ],
        ),
    ]
