# Generated by Django 5.0.7 on 2026-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Department',
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='school',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='substitution',
            old_name='school',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='school',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='customuser_subjects', to='school_management.subject'),
        ),
    ]
