# Generated by Django 5.0.6 on 2024-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitution",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Beschreibung"
            ),
        ),
        migrations.AlterField(
            model_name="personsubject",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Description"
            ),
        ),
    ]
