# Generated by Django 5.0.5 on 2024-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0002_substitution_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={
                "verbose_name": "Verfügbarkeit der Kandidaten",
                "verbose_name_plural": "Verfügbarkeit der Kandidaten",
            },
        ),
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["name"],
                "verbose_name": "Abschluss",
                "verbose_name_plural": "Abschlüsse",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["name"],
                "verbose_name": "Profil",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.AlterModelOptions(
            name="dayofweek",
            options={
                "ordering": ["id"],
                "verbose_name": "Wochentag",
                "verbose_name_plural": "Wochentage",
            },
        ),
        migrations.AlterModelOptions(
            name="gender",
            options={
                "ordering": ["name"],
                "verbose_name": "Geschlecht",
                "verbose_name_plural": "Geschlechter",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Lektion", "verbose_name_plural": "Lektionen"},
        ),
        migrations.AlterModelOptions(
            name="lessontemplate",
            options={
                "verbose_name": "Lektion-Template",
                "verbose_name_plural": "Lektion-Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ["name"],
                "verbose_name": "Stufe",
                "verbose_name_plural": "Stufen",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "Ort",
                "verbose_name_plural": "Orte",
            },
        ),
        migrations.AlterModelOptions(
            name="period",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Periode",
                "verbose_name_plural": "Perioden",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
            },
        ),
        migrations.AlterModelOptions(
            name="personcertificate",
            options={
                "verbose_name": "Zuordnung Abschluss zu Person",
                "verbose_name_plural": "Zuordnung Abschluss zu Person",
            },
        ),
        migrations.AlterModelOptions(
            name="personsubject",
            options={
                "verbose_name": "Zuordnung Fach zu Person",
                "verbose_name_plural": "Zuordnung Fach zu Person",
            },
        ),
        migrations.AlterModelOptions(
            name="school",
            options={
                "ordering": ["name"],
                "verbose_name": "Standort",
                "verbose_name_plural": "Standorte",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolclass",
            options={"verbose_name": "Klasse", "verbose_name_plural": "Klassen"},
        ),
        migrations.AlterModelOptions(
            name="schoolperson",
            options={
                "verbose_name": "Zuordnung Person zu Schule",
                "verbose_name_plural": "Zuordnung Person zu Schule",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolpersonrole",
            options={
                "ordering": ["name"],
                "verbose_name": "Rolle in Schule",
                "verbose_name_plural": "Rollen in Schule",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolyear",
            options={
                "ordering": ["year_start"],
                "verbose_name": "Schuljahr",
                "verbose_name_plural": "Schuljahre",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["name"],
                "verbose_name": "Fach",
                "verbose_name_plural": "Fächer",
            },
        ),
        migrations.AlterModelOptions(
            name="substitution",
            options={
                "verbose_name": "Stellvertretung",
                "verbose_name_plural": "Stellvertretungen",
            },
        ),
        migrations.AlterModelOptions(
            name="substitutioncause",
            options={
                "ordering": ["name"],
                "verbose_name": "Code für Abwesenheitsgrund",
                "verbose_name_plural": "Codes für Abwesenheitsgrund",
            },
        ),
        migrations.AlterModelOptions(
            name="substitutionperiod",
            options={
                "verbose_name": "Vertretung-Periode",
                "verbose_name_plural": "Vertretung-Perioden",
            },
        ),
        migrations.AlterModelOptions(
            name="timeofday",
            options={
                "ordering": ["-name"],
                "verbose_name": "Vormittag/Nachmittag",
                "verbose_name_plural": "Vormittag/Nachmittag",
            },
        ),
        migrations.AlterModelOptions(
            name="vacationtemplate",
            options={"verbose_name": "Ferien", "verbose_name_plural": "Ferien"},
        ),
        migrations.RemoveField(
            model_name="vacationtemplate",
            name="description",
        ),
        migrations.AddField(
            model_name="schoolyear",
            name="start_date",
            field=models.DateField(
                default="2024-01-01", verbose_name="Erster Schultag"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolyear",
            name="year_start",
            field=models.SmallIntegerField(default=2024, verbose_name="Jahr"),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Standort"),
        ),
    ]
