# Generated by Django 5.0.5 on 2024-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0003_alter_availability_options_alter_certificate_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationtemplate",
            name="name",
            field=models.CharField(
                default="test", max_length=255, verbose_name="Bezeichnung"
            ),
            preserve_default=False,
        ),
    ]
