# Generated by Django 5.0.7 on 2024-11-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0003_remove_school_plz"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.CreateModel(
            name="Location",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school_management.code",),
        ),
    ]
