# Generated by Django 5.0.5 on 2024-05-26 13:30

import django.db.models.deletion
import school_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0004_vacationtemplate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationday",
            name="timeofday",
            field=models.ForeignKey(
                default=school_management.models.get_default_time_of_day,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacation_time_of_day",
                to="school_management.timeofday",
            ),
        ),
        migrations.AlterField(
            model_name="vacationtemplate",
            name="timeofday",
            field=models.ForeignKey(
                default=school_management.models.get_default_time_of_day,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacation_template_time_of_day",
                to="school_management.timeofday",
            ),
        ),
    ]
