# Generated by Django 5.0.7 on 2024-11-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0004_delete_location_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="school_management.location",
                verbose_name="Ort",
            ),
        ),
    ]
