# Generated by Django 5.0.7 on 2024-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0005_alter_school_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Code"),
        ),
    ]
