# Generated by Django 5.0.5 on 2024-05-26 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0005_vacationday_timeofday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacationday",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Datum"
            ),
        ),
        migrations.AlterField(
            model_name="vacationtemplate",
            name="date_from",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Von"
            ),
        ),
        migrations.AlterField(
            model_name="vacationtemplate",
            name="date_to",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Bis"
            ),
        ),
        migrations.AlterField(
            model_name="vacationtemplate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Bezeichnung"),
        ),
    ]
