# Generated by Django 5.0.7 on 2024-11-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0007_rename_phone_number_person_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="send_email",
        ),
        migrations.RemoveField(
            model_name="person",
            name="send_sms",
        ),
    ]
