# Generated by Django 5.0.5 on 2024-05-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0007_substitutionperiod_confirmed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Availability",
            new_name="AvailabilityTemplate",
        ),
        migrations.AlterField(
            model_name="person",
            name="cv_file",
            field=models.FileField(
                blank=True, upload_to="cv/", verbose_name="CV Datei"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_candidate",
            field=models.BooleanField(
                default=False, verbose_name="KandidatIn für Stellvertretung"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="LehrerIn"),
        ),
        migrations.AlterField(
            model_name="person",
            name="years_of_experience",
            field=models.IntegerField(
                blank=True, default=1, verbose_name="Erfahrung in Jahren"
            ),
        ),
        migrations.CreateModel(
            name="SubstitutionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=1, verbose_name="Bewertung")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_candidates_persons",
                        to="school_management.person",
                    ),
                ),
                (
                    "substitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_candidates",
                        to="school_management.substitution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vertretung-KandidatIn",
                "verbose_name_plural": "Vertretung-Kandidaten",
            },
        ),
    ]
