# Generated by Django 5.0.5 on 2024-05-30 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0008_rename_availability_availabilitytemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_availabilities",
                to="school_management.person",
                verbose_name="Kandidat*in",
            ),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="day_of_week",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_availabilities_days",
                to="school_management.dayofweek",
            ),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="time_of_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_availabilities_time_of_day",
                to="school_management.timeofday",
            ),
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tag")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="school_management.person",
                        verbose_name="Kandidat*in",
                    ),
                ),
                (
                    "time_of_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities_time_of_day",
                        to="school_management.timeofday",
                    ),
                ),
            ],
        ),
    ]
