# Generated by Django 5.0.6 on 2025-12-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0008_remove_person_send_email_remove_person_send_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="untis_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="untis_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="untis_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="timeperiod",
            name="untis_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="year_start",
            field=models.SmallIntegerField(default=2025, verbose_name="Jahr"),
        ),
    ]
