# Generated by Django 5.0.6 on 2025-12-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0009_person_untis_id_schoolclass_untis_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemVariable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school_management.code",),
        ),
        migrations.AlterField(
            model_name="person",
            name="year_of_birth",
            field=models.IntegerField(
                blank=True, max_length=255, verbose_name="Jahrgang"
            ),
        ),
    ]
