# Generated by Django 5.0.5 on 2024-05-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0009_alter_availabilitytemplate_candidate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="is_leitung",
            new_name="is_manager",
        ),
    ]
