# Generated by Django 5.0.5 on 2024-05-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0010_rename_is_leitung_person_is_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school_management.person",),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school_management.person",),
        ),
        migrations.AddField(
            model_name="person",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to="school_management.subject"
            ),
        ),
    ]
