# Generated by Django 5.0.5 on 2024-06-03 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0011_candidate_teacher_person_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubstitutionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
            ],
            options={
                "verbose_name": "Status der Stellvertretung",
                "verbose_name_plural": "Status der Stellvertretungen",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_templates_candidate",
                to="school_management.person",
                verbose_name="Kandidat*in",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="person_subjects",
                to="school_management.subject",
            ),
        ),
    ]
