# Generated by Django 5.0.6 on 2025-12-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0011_alter_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="year_of_birth",
            field=models.IntegerField(blank=True, null=True, verbose_name="Jahrgang"),
        ),
    ]
