# Generated by Django 5.0.5 on 2024-06-03 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0012_substitutionstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitution",
            name="status",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="substitution_status",
                to="school_management.substitutionstatus",
            ),
        ),
    ]
