# Generated by Django 5.0.5 on 2024-06-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0013_substitution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitutioncandidate",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Bemerkungen"),
        ),
    ]
