# Generated by Django 5.0.5 on 2024-06-07 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0014_substitutioncandidate_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitution",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitution_schools",
                to="school_management.school",
                verbose_name="Schule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="Vorname"),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefonnummer"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="year_of_birth",
            field=models.CharField(blank=True, max_length=255, verbose_name="Jahrgang"),
        ),
    ]
