# Generated by Django 5.0.5 on 2024-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0015_substitution_school_alter_person_first_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Qualifikation"),
                ),
            ],
            options={
                "verbose_name": "Abschluss",
                "verbose_name_plural": "Abschlüsse",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="substitution",
            name="comment_class",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Anmerkung zur Klasse"
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="comment_subsitution",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Anmerkung zum Vikariat"
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="partial_substitution_possible",
            field=models.BooleanField(default=False, verbose_name="Teilübernahme"),
        ),
    ]
