# Generated by Django 5.0.5 on 2024-06-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0016_qualification_substitution_comment_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitution",
            name="minimum_qualification",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitution_certificates",
                to="school_management.qualification",
                verbose_name="Mindestabschluss",
            ),
        ),
    ]
