# Generated by Django 5.0.5 on 2024-06-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0018_remove_substitution_end_period_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="substitution",
            name="description",
        ),
        migrations.AddField(
            model_name="substitution",
            name="classes",
            field=models.TextField(blank=True, max_length=500, verbose_name="Klassen"),
        ),
        migrations.AddField(
            model_name="substitution",
            name="fr_afternoon",
            field=models.BooleanField(default=False, verbose_name="Freitag Nachmittag"),
        ),
        migrations.AddField(
            model_name="substitution",
            name="fr_monday",
            field=models.BooleanField(default=False, verbose_name="Freitag Vormittag"),
        ),
        migrations.AddField(
            model_name="substitution",
            name="mo_afternoon",
            field=models.BooleanField(default=False, verbose_name="Montag Nachmittag"),
        ),
        migrations.AddField(
            model_name="substitution",
            name="mo_monday",
            field=models.BooleanField(default=False, verbose_name="Montag Vormittag"),
        ),
        migrations.AddField(
            model_name="substitution",
            name="th_afternoon",
            field=models.BooleanField(
                default=False, verbose_name="Donnerstag Nachmittag"
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="th_monday",
            field=models.BooleanField(
                default=False, verbose_name="Donnerstag Vormittag"
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="tu_afternoon",
            field=models.BooleanField(
                default=False, verbose_name="Dienstag Nachmittag"
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="tu_monday",
            field=models.BooleanField(default=False, verbose_name="Dienstag Vormittag"),
        ),
        migrations.AddField(
            model_name="substitution",
            name="we_afternoon",
            field=models.BooleanField(
                default=False, verbose_name="Mittwoch Nachmittag"
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="we_monday",
            field=models.BooleanField(default=False, verbose_name="Mittwoch Vormittag"),
        ),
    ]
