# Generated by Django 5.0.5 on 2024-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0019_remove_substitution_description_substitution_classes_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="substitution",
            old_name="fr_monday",
            new_name="fr_morning",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="th_monday",
            new_name="th_morning",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="tu_monday",
            new_name="tu_morning",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="we_monday",
            new_name="we_morning",
        ),
        migrations.RemoveField(
            model_name="substitution",
            name="mo_monday",
        ),
        migrations.AddField(
            model_name="substitution",
            name="mo_morning",
            field=models.BooleanField(default=False, verbose_name="Montag Vormittag"),
        ),
    ]
