# Generated by Django 5.0.5 on 2024-06-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0020_rename_fr_monday_substitution_fr_morning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="availability_comment",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Bemerkungen zur Verfügbarkeit"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_fr_am",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_fr_pm",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_mo_am",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_mo_pm",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_th_am",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_th_pm",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_tu_am",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_tu_pm",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_we_am",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_we_pm",
            field=models.BooleanField(default=False, verbose_name="Montag Morgen"),
        ),
        migrations.AddField(
            model_name="person",
            name="available_from_date",
            field=models.DateField(blank=True, null=True, verbose_name="Verfügbar ab"),
        ),
        migrations.AddField(
            model_name="person",
            name="available_to_date",
            field=models.DateField(blank=True, null=True, verbose_name="Verfügbar ab"),
        ),
    ]
