# Generated by Django 5.0.5 on 2024-06-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0021_person_availability_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="substitution",
            old_name="fr_morning",
            new_name="fr_am",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="fr_afternoon",
            new_name="fr_pm",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="mo_morning",
            new_name="mo_am",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="mo_afternoon",
            new_name="mo_pm",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="th_morning",
            new_name="th_am",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="th_afternoon",
            new_name="th_pm",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="tu_morning",
            new_name="tu_am",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="tu_afternoon",
            new_name="tu_pm",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="we_morning",
            new_name="we_am",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="we_afternoon",
            new_name="we_pm",
        ),
    ]
