# Generated by Django 5.0.5 on 2024-06-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0022_rename_fr_morning_substitution_fr_am_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_schools",
                to="school_management.school",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_fr_am",
            field=models.BooleanField(default=False, verbose_name="Freitag Vormittag"),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_fr_pm",
            field=models.BooleanField(default=False, verbose_name="Freitag Nachmittag"),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_mo_am",
            field=models.BooleanField(default=False, verbose_name="Montag Vormittag"),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_mo_pm",
            field=models.BooleanField(default=False, verbose_name="Montag Nachmittag"),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_th_am",
            field=models.BooleanField(
                default=False, verbose_name="Donnerstag Vormittag"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_th_pm",
            field=models.BooleanField(
                default=False, verbose_name="Donnerstag Nachmittag"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_tu_am",
            field=models.BooleanField(default=False, verbose_name="Dienstag Vormittag"),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_tu_pm",
            field=models.BooleanField(
                default=False, verbose_name="Dienstag Nachmittag"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_we_am",
            field=models.BooleanField(default=False, verbose_name="Mittwoch Vormittag"),
        ),
        migrations.AlterField(
            model_name="person",
            name="availability_we_pm",
            field=models.BooleanField(
                default=False, verbose_name="Mittwoch Nachmittag"
            ),
        ),
    ]
