# Generated by Django 5.0.5 on 2024-06-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0023_person_school_alter_person_availability_fr_am_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="cv_file",
        ),
        migrations.RemoveField(
            model_name="person",
            name="cv_text",
        ),
        migrations.RemoveField(
            model_name="person",
            name="years_of_experience",
        ),
    ]
