# Generated by Django 5.0.5 on 2024-06-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0024_remove_person_cv_file_remove_person_cv_text_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonSubject",
        ),
    ]
