# Generated by Django 5.0.5 on 2024-06-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0025_delete_personsubject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="school_year",
        ),
    ]
