# Generated by Django 5.0.5 on 2024-06-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0028_remove_substitutionperiod_lesson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="cycle_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Zyklus-Name"
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="cycle_name_short",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Kurz-Zyklus-Name"
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="name_short",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Kurz-Name"
            ),
        ),
    ]
