# Generated by Django 5.0.5 on 2024-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0029_level_cycle_name_level_cycle_name_short_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitution",
            name="levels",
            field=models.TextField(blank=True, max_length=500, verbose_name="Stufen"),
        ),
        migrations.AddField(
            model_name="substitution",
            name="subjects",
            field=models.TextField(blank=True, max_length=500, verbose_name="Fächer"),
        ),
    ]
