# Generated by Django 5.0.5 on 2024-06-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0030_substitution_levels_substitution_subjects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayofweek",
            old_name="short_name",
            new_name="name_short",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="short_name",
            new_name="name_short",
        ),
    ]
