# Generated by Django 5.0.5 on 2024-06-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0032_delete_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Von")),
                ("date_to", models.DateField(verbose_name="Bis")),
                (
                    "mo_am",
                    models.BooleanField(default=False, verbose_name="Montag Vormittag"),
                ),
                (
                    "mo_pm",
                    models.BooleanField(
                        default=False, verbose_name="Montag Nachmittag"
                    ),
                ),
                (
                    "tu_am",
                    models.BooleanField(
                        default=False, verbose_name="Dienstag Vormittag"
                    ),
                ),
                (
                    "tu_pm",
                    models.BooleanField(
                        default=False, verbose_name="Dienstag Nachmittag"
                    ),
                ),
                (
                    "we_am",
                    models.BooleanField(
                        default=False, verbose_name="Mittwoch Vormittag"
                    ),
                ),
                (
                    "we_pm",
                    models.BooleanField(
                        default=False, verbose_name="Mittwoch Nachmittag"
                    ),
                ),
                (
                    "th_am",
                    models.BooleanField(
                        default=False, verbose_name="Donnerstag Vormittag"
                    ),
                ),
                (
                    "th_pm",
                    models.BooleanField(
                        default=False, verbose_name="Donnerstag Nachmittag"
                    ),
                ),
                (
                    "fr_am",
                    models.BooleanField(
                        default=False, verbose_name="Freitag Vormittag"
                    ),
                ),
                (
                    "fr_pm",
                    models.BooleanField(
                        default=False, verbose_name="Freitag Nachmittag"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_templates_candidate",
                        to="school_management.person",
                        verbose_name="Kandidat*in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verfügbarkeit der Kandidaten",
                "verbose_name_plural": "Verfügbarkeit der Kandidaten",
            },
        ),
        migrations.DeleteModel(
            name="AvailabilityTemplate",
        ),
    ]
