# Generated by Django 5.0.5 on 2024-06-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0033_availability_delete_availabilitytemplate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Availability",
        ),
    ]
