# Generated by Django 5.0.5 on 2024-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0035_substitutioncandidate_matching_half_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitutioncandidate",
            name="num_experiences",
            field=models.IntegerField(default=0, verbose_name="Anzahl Erfahrungen"),
        ),
    ]
