# Generated by Django 5.0.5 on 2024-06-23 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0036_substitutioncandidate_num_experiences"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitution",
            name="selection_comment",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Kommentar zur Besetzung"
            ),
        ),
        migrations.AddField(
            model_name="substitutioncandidate",
            name="accepted_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Bestätigung am"
            ),
        ),
        migrations.AddField(
            model_name="substitutioncandidate",
            name="invited_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Einladungsdatum"
            ),
        ),
        migrations.AddField(
            model_name="substitutioncandidate",
            name="selected_date",
            field=models.DateField(blank=True, null=True, verbose_name="Zusage"),
        ),
    ]
