# Generated by Django 5.0.5 on 2024-06-23 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0037_substitution_selection_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitutioncandidate",
            name="record_created_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Erstellt am"
            ),
        ),
        migrations.AlterField(
            model_name="substitutioncandidate",
            name="invited_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Einladungsdatum"
            ),
        ),
    ]
