# Generated by Django 5.0.5 on 2024-06-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0038_substitutioncandidate_record_created_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="order",
            field=models.IntegerField(default=1, verbose_name="Reihenfolge"),
        ),
    ]
