# Generated by Django 5.0.5 on 2024-06-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0039_level_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitution",
            name="summary",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Zusammenfassung"
            ),
        ),
    ]
