# Generated by Django 5.0.5 on 2024-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0040_substitution_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="email",
            field=models.EmailField(blank=True, max_length=255, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="school",
            name="mobile",
            field=models.CharField(blank=True, max_length=255, verbose_name="Mobile"),
        ),
        migrations.AddField(
            model_name="school",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Telefonnummer"
            ),
        ),
        migrations.AlterField(
            model_name="substitution",
            name="partial_substitution_possible",
            field=models.BooleanField(
                default=False, verbose_name="Teilübernahme möglich"
            ),
        ),
    ]
