# Generated by Django 5.0.5 on 2024-06-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0041_school_email_school_mobile_school_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.RemoveField(
            model_name="schoolperson",
            name="person",
        ),
        migrations.RemoveField(
            model_name="schoolperson",
            name="role",
        ),
        migrations.RemoveField(
            model_name="schoolperson",
            name="school",
        ),
        migrations.AddField(
            model_name="person",
            name="teacherid",
            field=models.IntegerField(blank=True, null=True, verbose_name="Lehrer-ID"),
        ),
        migrations.DeleteModel(
            name="PersonCertificate",
        ),
        migrations.DeleteModel(
            name="SchoolPerson",
        ),
    ]
