# Generated by Django 5.0.5 on 2024-06-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0042_delete_course_remove_schoolperson_person_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonTemplate",
            new_name="Timetable",
        ),
    ]
