# Generated by Django 5.0.5 on 2024-06-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0043_rename_lessontemplate_timetable"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VacationTemplate",
            new_name="Vacation",
        ),
    ]
