# Generated by Django 5.0.6 on 2024-07-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_management",
            "0048_remove_person_school_remove_person_teacherid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="gender",
        ),
    ]
