# Generated by Django 5.0.6 on 2024-07-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0050_subject_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='contact_person',
        ),
    ]
