# Generated by Django 5.0.7 on 2024-08-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0057_alter_communication_response_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="gender",
        ),
    ]
