# Generated by Django 5.0.7 on 2024-08-22 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0058_remove_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_management.gender",
            ),
        ),
    ]
