# Generated by Django 5.0.7 on 2024-11-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0061_alter_communication_response_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="send_email",
            field=models.BooleanField(
                default=True, verbose_name="Kommunikation per Email erwünscht"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="send_sms",
            field=models.BooleanField(
                default=True, verbose_name="Kommunikation per SMS erwünscht"
            ),
        ),
    ]
