# Generated by Django 5.0.7 on 2024-11-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0063_person_selected_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="selected_candidate",
        ),
    ]
