# Generated by Django 5.0.7 on 2024-11-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0064_remove_person_selected_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="schools",
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_management.gender",
                verbose_name="Geschlecht",
            ),
        ),
    ]
