# Generated by Django 5.0.7 on 2024-11-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0065_remove_person_schools_alter_person_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semester",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="send_email",
            field=models.BooleanField(
                default=True, verbose_name="Kommunikation mit Email erwünscht"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="send_sms",
            field=models.BooleanField(
                default=True, verbose_name="Kommunikation mit SMS erwünscht"
            ),
        ),
    ]
