# Generated by Django 5.0.7 on 2024-11-12 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0067_timetable_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="comment",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Kommentar"
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="response_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Antwort am",
            ),
        ),
    ]
