# Generated by Django 5.0.7 on 2024-11-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0069_alter_communication_response_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communication",
            old_name="comment",
            new_name="comments",
        ),
    ]
