# Generated by Django 5.0.7 on 2024-11-12 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0070_rename_comment_communication_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Bewertung",
            ),
        ),
    ]
