# Generated by Django 5.0.7 on 2024-11-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0071_communication_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="availability_comment",
            field=models.TextField(
                blank=True,
                max_length=1000,
                verbose_name="Bemerkungen zur Verfügbarkeit",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Bemerkungen"
            ),
        ),
    ]
