# Generated by Django 5.0.7 on 2024-11-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0072_alter_person_availability_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="comments",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Kommentar"
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="request_text",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Anfrage"),
        ),
        migrations.AlterField(
            model_name="communication",
            name="response_text",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Antwort"),
        ),
        migrations.AlterField(
            model_name="substitution",
            name="classes",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Klassen"),
        ),
        migrations.AlterField(
            model_name="substitution",
            name="comment_class",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Anmerkung zur Klasse"
            ),
        ),
        migrations.AlterField(
            model_name="substitution",
            name="comment_subsitution",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Anmerkung zum Vikariat"
            ),
        ),
        migrations.AlterField(
            model_name="substitution",
            name="levels",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Stufen"),
        ),
        migrations.AlterField(
            model_name="substitution",
            name="selection_comment",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Kommentar zur Besetzung"
            ),
        ),
        migrations.AlterField(
            model_name="substitution",
            name="subjects",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Fächer"),
        ),
    ]
