# Generated by Django 5.0.7 on 2024-11-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0073_alter_communication_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substitution",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_substitutions",
                to="school_management.teacher",
                verbose_name="Lehrkraft",
            ),
        ),
        migrations.CreateModel(
            name="SubstitutionLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_lessons_candidates",
                        to="school_management.candidate",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_days",
                        to="school_management.dayofweek",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_periods",
                        to="school_management.period",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_school_classes",
                        to="school_management.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_subjects",
                        to="school_management.subject",
                    ),
                ),
                (
                    "substitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_lessons",
                        to="school_management.substitution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lektion",
                "verbose_name_plural": "Lektionen",
            },
        ),
    ]
