# Generated by Django 5.0.7 on 2024-11-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0074_alter_substitution_teacher_substitutionlesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="substitution",
            old_name="classes",
            new_name="classes_cli",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="levels",
            new_name="levels_cli",
        ),
        migrations.RenameField(
            model_name="substitution",
            old_name="subjects",
            new_name="subjects_cli",
        ),
    ]
