# Generated by Django 5.0.7 on 2024-11-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0075_rename_classes_substitution_classes_cli_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substitutionlesson",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitution_lessons_candidates",
                to="school_management.candidate",
            ),
        ),
    ]
