# Generated by Django 5.0.7 on 2024-11-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0077_substitution_durchfuehrung1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="substitution",
            name="durchfuehrung1",
        ),
        migrations.RemoveField(
            model_name="substitution",
            name="durchfuehrung2",
        ),
    ]
