# Generated by Django 5.0.7 on 2024-11-19 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0078_remove_substitution_durchfuehrung1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubstitutionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Bewertung",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Kommentar"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_executions_candidates",
                        to="school_management.candidate",
                    ),
                ),
                (
                    "substitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_executions",
                        to="school_management.substitution",
                    ),
                ),
            ],
        ),
    ]
