# Generated by Django 5.0.7 on 2024-11-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0079_substitutionexecution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="substitution",
            name="selection_comment",
        ),
    ]
