# Generated by Django 5.0.7 on 2024-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0080_remove_substitution_selection_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communication",
            name="rating",
        ),
        migrations.AlterField(
            model_name="communication",
            name="comments",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Bemerkungen"
            ),
        ),
    ]
